[package]
name = "olavm-plonky2"
version = "0.1.0"
description = "OlaVM custom plonky2"
readme = "README.md"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
